/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/utils/hub.py:105: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py:898: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:476: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]Fetching 8 files:  38%|███▊      | 3/8 [00:00<00:00,  5.60it/s]
Traceback (most recent call last):
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 416 Client Error: Requested Range Not Satisfiable for url: https://cdn-lfs-us-1.hf.co/repos/a4/22/a422c2be72659401d7e5d8e2448832c5f4b9f51f227e072b88cb7e204c22f193/f4aa5f7d5510456fba5eb22421432a65487b1d0864fbd59ca6f8dfac65184d32?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model-00004-of-00008.safetensors%3B+filename%3D%22model-00004-of-00008.safetensors%22%3B&Expires=1746007434&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc0NjAwNzQzNH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zL2E0LzIyL2E0MjJjMmJlNzI2NTk0MDFkN2U1ZDhlMjQ0ODgzMmM1ZjRiOWY1MWYyMjdlMDcyYjg4Y2I3ZTIwNGMyMmYxOTMvZjRhYTVmN2Q1NTEwNDU2ZmJhNWViMjI0MjE0MzJhNjU0ODdiMWQwODY0ZmJkNTljYTZmOGRmYWM2NTE4NGQzMj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=rcLhBkueyS7uyiX9SMBCg1qPBrhppgxmW5FrOpKxvO9ZTArnmNJrcCu590rIqJ113rWXq6tHmC1-CoQfPp2O6S3NzpSH7vSLEFLl2wEe3IK4Bbt20kdlgTCtUTrfvmFsZamhl4HB31avU6hExEePb~2vKBjxu5G8ZgT5B11IakVTZ3MRFPT~V53gQmEw~nkT65Zudov2n0trlsappSiLYxihxwEWhETAU8aCzWDroAZg1phT-HBhwCKidtXsewPHZl-bxTX3-74bQHZI3wsJyXkStRTck4Dj4uDsrrxOMPi1xRc23zELWQsH11aJ-QzmEGLgkuYoU5DxmGFGiIv0aw__&Key-Pair-Id=K24J24Z295AEI9

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/utils/hub.py", line 439, in cached_files
    snapshot_download(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 296, in snapshot_download
    thread_map(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 270, in _inner_hf_hub_download
    return hf_hub_download(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 961, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1112, in _hf_hub_download_to_cache_dir
    _download_to_tmp_and_move(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1675, in _download_to_tmp_and_move
    http_get(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 376, in http_get
    r = _request_wrapper(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 309, in _request_wrapper
    hf_raise_for_status(response)
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 478, in hf_raise_for_status
    raise _format(HfHubHTTPError, message, response) from e
huggingface_hub.errors.HfHubHTTPError: 416 Client Error: Requested Range Not Satisfiable for url: https://cdn-lfs-us-1.hf.co/repos/a4/22/a422c2be72659401d7e5d8e2448832c5f4b9f51f227e072b88cb7e204c22f193/f4aa5f7d5510456fba5eb22421432a65487b1d0864fbd59ca6f8dfac65184d32?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model-00004-of-00008.safetensors%3B+filename%3D%22model-00004-of-00008.safetensors%22%3B&Expires=1746007434&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc0NjAwNzQzNH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zL2E0LzIyL2E0MjJjMmJlNzI2NTk0MDFkN2U1ZDhlMjQ0ODgzMmM1ZjRiOWY1MWYyMjdlMDcyYjg4Y2I3ZTIwNGMyMmYxOTMvZjRhYTVmN2Q1NTEwNDU2ZmJhNWViMjI0MjE0MzJhNjU0ODdiMWQwODY0ZmJkNTljYTZmOGRmYWM2NTE4NGQzMj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=rcLhBkueyS7uyiX9SMBCg1qPBrhppgxmW5FrOpKxvO9ZTArnmNJrcCu590rIqJ113rWXq6tHmC1-CoQfPp2O6S3NzpSH7vSLEFLl2wEe3IK4Bbt20kdlgTCtUTrfvmFsZamhl4HB31avU6hExEePb~2vKBjxu5G8ZgT5B11IakVTZ3MRFPT~V53gQmEw~nkT65Zudov2n0trlsappSiLYxihxwEWhETAU8aCzWDroAZg1phT-HBhwCKidtXsewPHZl-bxTX3-74bQHZI3wsJyXkStRTck4Dj4uDsrrxOMPi1xRc23zELWQsH11aJ-QzmEGLgkuYoU5DxmGFGiIv0aw__&Key-Pair-Id=K24J24Z295AEI9. Requested range: bytes=5147189232-. Content-Range: None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/joberant_nobck/data/NLP_368307701_2425a/sharonsaban/NLP_FINAL_PROJECT/run_exp.py", line 220, in <module>
    main()
  File "/vol/joberant_nobck/data/NLP_368307701_2425a/sharonsaban/NLP_FINAL_PROJECT/run_exp.py", line 99, in main
    tokenizer, model, device = load_model(model_name, duplication_instructions)
  File "/vol/joberant_nobck/data/NLP_368307701_2425a/sharonsaban/NLP_FINAL_PROJECT/run_exp.py", line 65, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
    return model_class.from_pretrained(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
    return func(*args, **kwargs)
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4260, in from_pretrained
    checkpoint_files, sharded_metadata = _get_resolved_checkpoint_files(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1152, in _get_resolved_checkpoint_files
    checkpoint_files, sharded_metadata = get_checkpoint_shard_files(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/utils/hub.py", line 1115, in get_checkpoint_shard_files
    cached_filenames = cached_files(
  File "/home/joberant/NLP_2425a/sharonsaban/anaconda3/envs/sharon_env/lib/python3.10/site-packages/transformers/utils/hub.py", line 501, in cached_files
    raise OSError(f"There was a specific connection error when trying to load {path_or_repo_id}:\n{e}")
OSError: There was a specific connection error when trying to load google/gemma-2-9b:
416 Client Error: Requested Range Not Satisfiable for url: https://cdn-lfs-us-1.hf.co/repos/a4/22/a422c2be72659401d7e5d8e2448832c5f4b9f51f227e072b88cb7e204c22f193/f4aa5f7d5510456fba5eb22421432a65487b1d0864fbd59ca6f8dfac65184d32?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model-00004-of-00008.safetensors%3B+filename%3D%22model-00004-of-00008.safetensors%22%3B&Expires=1746007434&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc0NjAwNzQzNH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zL2E0LzIyL2E0MjJjMmJlNzI2NTk0MDFkN2U1ZDhlMjQ0ODgzMmM1ZjRiOWY1MWYyMjdlMDcyYjg4Y2I3ZTIwNGMyMmYxOTMvZjRhYTVmN2Q1NTEwNDU2ZmJhNWViMjI0MjE0MzJhNjU0ODdiMWQwODY0ZmJkNTljYTZmOGRmYWM2NTE4NGQzMj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=rcLhBkueyS7uyiX9SMBCg1qPBrhppgxmW5FrOpKxvO9ZTArnmNJrcCu590rIqJ113rWXq6tHmC1-CoQfPp2O6S3NzpSH7vSLEFLl2wEe3IK4Bbt20kdlgTCtUTrfvmFsZamhl4HB31avU6hExEePb~2vKBjxu5G8ZgT5B11IakVTZ3MRFPT~V53gQmEw~nkT65Zudov2n0trlsappSiLYxihxwEWhETAU8aCzWDroAZg1phT-HBhwCKidtXsewPHZl-bxTX3-74bQHZI3wsJyXkStRTck4Dj4uDsrrxOMPi1xRc23zELWQsH11aJ-QzmEGLgkuYoU5DxmGFGiIv0aw__&Key-Pair-Id=K24J24Z295AEI9. Requested range: bytes=5147189232-. Content-Range: None.
